### ISSUE TITLE
Add documentation how to install the app generator on Google Cloud - with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#1238]
The setup with Kubernetes is not documented yet. Please set up the system on Google Cloud and document it. Please share the link to your installation.

@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by sch00lb0y** [comment]
@mariobehling i would like to work on this issue. please assign this to me.Thanks
