### ISSUE TITLE
Make fonts work on the deployment itself - avoid getting fonts from external services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#1751]
We are using Google Fonts. Instead of getting fonts from the Google service implement the fonts statically as part of the web app.

**Comment by shubham3211** [comment]
I would like to work on this issue.

**Comment by aayusharora** [comment]
Hi @shubham3211, please go ahead.

**Comment by mariobehling** [comment]
While the Google fonts were removed it also resulted in a very different look of the page. We need the previous look of the fonts but having the fonts as part of the repo.

**Comment by pydevsg** [comment]
Hi @mariobehling , is this issue still open , can I cotribute in it
