### ISSUE TITLE
Field is secured to not store data - it should not

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2081]
The API field is created in a way to not store data. Usually a browser suggests to prefill a field. This is not the case here as the field is secured to not allow that. Please allow this.

![screenshot from 2018-08-23 12-03-07](https://user-images.githubusercontent.com/1583873/44504134-abc2a700-a6cc-11e8-971f-4d15723cd74f.png)

**Comment by darthgera123** [comment]
can i work on this issue?

**Comment by digitalPlayer1125** [comment]
The intended solution is what'd enable autocomplete [by browser, as shown in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url], right? or is it desired from a data source?

**Comment by iamareebjamal** [comment]
Yes
