### ISSUE TITLE
Header should be semi-transparent and not expanding on scroll over

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2085]
The header used to be semi-transparent and disappear on scroll up. Currently on scroll over menu items the bottom of the header also expands. Expected:

* Make header semi-transparen as https://fossasia.org
* Implement disappear on scroll up as on https://chat.susi.ai/overview
* Avoid expansion of height on scroll over menu items

**Comment by sarnava1** [comment]
can i work on this @mariobehling ?

**Comment by notlmn** [comment]
> - Avoid expansion of height on scroll over menu items

@mariobehling Can you provide a link to the page where this is happening?

**Comment by aliya-rahmani** [comment]
@mariobehling Can I still work on this issue?

**Comment by Raunaksingh100** [comment]
> @mariobehling Can I still work on this issue?

Yes this issue is still open you can work on this

**Comment by guptapranav4299** [comment]
I would like to work on this issue @mariobehling
