### ISSUE TITLE
'github' dependency renamed to '@octokit/rest'

### ISSUE THREAD

**Issue by pranav1698** [fossasia/open-event-wsgen#2113]
**Actual Behaviour**
After installing all dependencies, when trying to run `npm run start`:
There is an error occuring which is: 
`'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)`

**Expected Behaviour**
The "github" should be renamed to "@octokit/rest"

**Steps to reproduce it**
1. After cloning the latest branch of master
2. Install all dependencies
3. USE `npm run start`
4.See this unexpected error

**Log for the issue**
`'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)`

**Screenshots of the issue**
![screenshot from 2018-10-04 23-39-19](https://user-images.githubusercontent.com/34754265/46493738-c1300280-c82e-11e8-94e6-80dae5db21d3.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Seems this was solved already.
