### ISSUE TITLE
Organizer Information is missing on central 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2126]
If organizer info, code of conduct and license is chosen in event, it should be provided through the API that is used to generate an event web app. Currently the organizer information does not show up using https://eventyay.com/api/v1/events/324

![screenshot from 2018-11-14 17-23-30](https://user-images.githubusercontent.com/1583873/48496459-5365f600-e832-11e8-957b-1a9b65a8bca5.png)

**Comment by anjali1102** [comment]
Taking up this issue

**Comment by guptapranav4299** [comment]
@mariobehling  I would like to work on this issue.
We can add organizer info, code of conduct and license in a separate organizer json file or in the event json file and then render it on the web app.
