### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2128]
Travis is currently failing. Please help to fix it.

**Comment by Ananthavijay** [comment]
@mariobehling this is not yet fixed. Doing some research. Will open a PR soon
Thanks

**Comment by Dishebh** [comment]
Can you please show the logs for the error? That way, it would be easier to resolve the issue.

**Comment by kushthedude** [comment]
@mariobehling Still not solved

**Comment by iamareebjamal** [comment]
It was disabled instead of being fixed, hence reopening

**Comment by iamareebjamal** [comment]
Cause of test failures 

1. The images in sample are invalid

**Comment by Dishebh** [comment]
> Cause of test failures
> 
> 1. The images in sample are invalid

So, shall I remove the images (which are not being used currently) present in `docs/images`?

**Comment by iamareebjamal** [comment]
No, they need to be fixed

**Comment by Dishebh** [comment]
> No, they need to be fixed

Fixed, how?

**Comment by iamareebjamal** [comment]
I'm talking about image URLs in JSON

**Comment by Dishebh** [comment]
> I'm talking about image URLs in JSON

Can you pls cite the source of json file? Thanks
