### ISSUE TITLE
Error Generating Site with API v.1

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2134]
Using the API v.1 at https://eventyay.com/api/v1/events/598 the site generator shows an error at 70% completion: 

> ERROR:Error in compiling/writing templates, Error Compiling the html pages from the templates

![screenshot from 2019-02-17 16-32-50](https://user-images.githubusercontent.com/1583873/52910406-f2870780-32d1-11e9-9d4d-2ed351d7d9c0.png)

**Comment by mariobehling** [comment]
So, it works with the previous FOSSASIA event at https://eventyay.com/api/v1/events/275

**Comment by CosmicCoder96** [comment]
it was caused by a double quote in a speaker name.

**Comment by Aakash-DD** [comment]
It seems something like data must be stored in database and to be used when user are searching for the result...

**Comment by ms10398** [comment]
Is it working now @mariobehling or do we need anything done on this?

**Comment by mariobehling** [comment]
It is working now. One of the names had a special character which it did not accept. Closing it therefore. Thank you!
