### ISSUE TITLE
Address bottom bar area not aligned in one line and not aligned with middle bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2135]
The address area should be aligned in the same way as the left and middle bottom bar.

Also, the text should be behind the icon.

![screenshot from 2019-02-18 01-45-10](https://user-images.githubusercontent.com/1583873/52916808-fd1bbe00-331e-11e9-8e56-789c6122102b.png)

**Comment by Swayamsvk** [comment]
Is this issue open I want t work on this.

**Comment by Dishebh** [comment]
> Is this issue open I want t work on this.

Sure, go ahead

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by Raunaksingh100** [comment]
i am working on this issue
