### ISSUE TITLE
Organizer section showing html code and not following site design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2136]
Please fix the organizer section following design of site, e.g. add space at section end. Also fix html display.

![screenshot from 2019-02-18 01-44-08](https://user-images.githubusercontent.com/1583873/52916832-39e7b500-331f-11e9-8e38-700067e10b27.png)

**Comment by asha15** [comment]
@mariobehling Shall i work on this?

**Comment by pranavkarthik10** [comment]
Fixed this issue, https://github.com/fossasia/open-event-wsgen/pull/2149.
