### ISSUE TITLE
Schedule page sessions width and area not same as on tracks.html

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2137]
Please ensure the sessions page are the same as the tracks.html page, e.g. make it full width using the area available.

Compare schedule page;
![screenshot from 2019-02-18 01-58-58](https://user-images.githubusercontent.com/1583873/52916993-f7bf7300-3320-11e9-9338-bfd88ab5242c.png)

to tracks page. It should look the same!
![screenshot from 2019-02-18 01-58-34](https://user-images.githubusercontent.com/1583873/52917001-073ebc00-3321-11e9-9ba0-f5f3cf9e0b9c.png)

**Comment by NamanZelawat** [comment]
I would like to fix this can anyone help with the source code.

**Comment by kushthedude** [comment]
> I would like to fix this can anyone help with the source code.

You are in the repository itself, Click on code tab for source code

**Comment by iamareebjamal** [comment]
Reopening since the PR broke many things and has been reverted

**Comment by b2pacific** [comment]
I would like to work on this issue.
