### ISSUE TITLE
Direct Link to session hides time and session name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2138]
E.g. check out the link: https://2019.fossasia.org/event/schedule.html#5078

Expected: A direct link should show the top of the session just below the top bar.

![screenshot from 2019-02-18 13-34-53](https://user-images.githubusercontent.com/1583873/52930101-130e9a80-3382-11e9-864f-0d91fb15a2cf.png)

**Comment by Hackerbone** [comment]
I would like to work on this!

**Comment by Hackerbone** [comment]
Should I do this addition in the 2019.fossasia.org repo ?

**Comment by djcruz93** [comment]
@mariobehling @iamareebjamal A direct bookmark link is working fine on the development branch. Do let me know if I am missing something to reproduce it.
