### ISSUE TITLE
Cannot open sidebar filter in new tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2139]
It is currently not possible to open the sidebar filter links as real links in a new tab.

![screenshot from 2019-02-18 14-34-35](https://user-images.githubusercontent.com/1583873/52932414-9338fe00-338a-11e9-9303-76ca31dc1499.png)

**Comment by ms10398** [comment]
I would like to work on this

**Comment by kushthedude** [comment]
@mariobehling Claiming this issue.

**Comment by NamanZelawat** [comment]
Can anyone help me in searching the codebase for the above specified page?

**Comment by NamanZelawat** [comment]
I would like to fix it.

**Comment by Dishebh** [comment]
@mariobehling why is it necessary, I mean why do we need to implement it?

**Comment by todi-2000** [comment]
Can I work on this issue?

**Comment by djcruz93** [comment]
@iamareebjamal @mariobehling I would like to take up this issue. It seems like no one is working on it at present.
