### ISSUE TITLE
Website Link inside Readme not working

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-wsgen#2141]
The link `http://sched.eventyay.com` provided in the Readme.md file is not working.

**Comment by sarthakpranesh** [comment]
Hey, I would love to help. Just gave readme a visit, the link is working fine.
Is it still not working for you?

**Comment by Raunaksingh100** [comment]
@mariobehling i am working on this issue can you plz add the codeheat label for this ??

**Comment by Subham142** [comment]
@mariobehling  I think its working ,on clicking the link in the readme , we are forwarded  to this page
![Screenshot (54)](https://user-images.githubusercontent.com/60570595/98558215-2d617800-22cb-11eb-9b82-5efd2b6fc5d6.png)

**Comment by Subham142** [comment]
please correct me if I am wrong

**Comment by aayusharora** [comment]
Yes, thanks.
