### ISSUE TITLE
Update the readme badges

### ISSUE THREAD

**Issue by Dishebh** [fossasia/open-event-wsgen#2151]
**Actual Behaviour**

The codeclimate and heroku badge respond with a 404 error.  

**Expected Behaviour**

Update the above mentioned badges. 

**Steps to reproduce it**

Go to the readme file and you'll see the badges at the top.

**Screenshots of the issue**
![Screenshot from 2019-12-30 17-03-46](https://user-images.githubusercontent.com/43489708/71580382-7468d380-2b26-11ea-8f13-4ef4e45f941c.png)

**Comment by hoangdatngo** [comment]
@Dishebh I want to work on this issue

**Comment by Dishebh** [comment]
Sure, go ahead.

**Comment by hoangdatngo** [comment]
@Dishebh Thanks
