### ISSUE TITLE
Navbar isn't fixed at top

### ISSUE THREAD

**Issue by Dishebh** [fossasia/open-event-wsgen#2155]
**Actual Behaviour**

Nav menu doesn't remain fixed at top, while scrolling
**Expected Behaviour**

Navbar should be fixed
**Steps to reproduce it**

- Go to the [website](http://scged.eventyay.com)
- You'll see the navbar doesn't remain fixed

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
The idea of the navigation bar was to have it similar to eventyay.com. This issue would mean we move away from this idea. What we actually need in this project is to resolve Travis CI errors and to get the generator working with the latest API version. It does not help the project so much, if you come up with more of these issues here. We need the site generation to work asap. Please help with that. Thanks!
