### ISSUE TITLE
Speaker bio not aligned properly

### ISSUE THREAD

**Issue by Dishebh** [fossasia/open-event-wsgen#2158]
**Actual Behaviour**
Speaker bio not aligned properly with image

**Expected Behaviour**
The alignement should be proper and uniform

**Screenshots of the issue**
![Screenshot from 2020-01-06 14-17-23](https://user-images.githubusercontent.com/43489708/71806709-8222d980-308f-11ea-8079-177b295c80c7.png)

**Would you like to work on the issue?**
yes

**Comment by ektaarora3501** [comment]
Hey can I work on this issue ?

**Comment by Dishebh** [comment]
Sure, go ahead

**Comment by ektaarora3501** [comment]
![Screen Shot 2020-01-09 at 18 56 01](https://user-images.githubusercontent.com/42875737/72071441-cf15e280-3311-11ea-96e6-693a6eee7199.png)
will this go @Dishebh

**Comment by ektaarora3501** [comment]
Will this go @Dishebh 
![Screenshot from 2020-01-09 19-02-07](https://user-images.githubusercontent.com/42875737/72071796-9fb3a580-3312-11ea-8b3f-87605eef7325.png)

**Comment by Dishebh** [comment]
Can you please show the result in different screen resolutions as well?

**Comment by ektaarora3501** [comment]
![Screenshot from 2020-01-09 19-27-11](https://user-images.githubusercontent.com/42875737/72073597-3cc40d80-3316-11ea-8156-4b0071ec26fe.png)
Check this please

**Comment by Dishebh** [comment]
> Will this go @Dishebh ?
> ![Screenshot from 2020-01-09 19-02-07](https://user-images.githubusercontent.com/42875737/72071796-9fb3a580-3312-11ea-8b3f-87605eef7325.png)

Can you limit the sentence length to the image width?

**Comment by ektaarora3501** [comment]
Will it go ?
![Screenshot from 2020-01-09 20-40-51](https://user-images.githubusercontent.com/42875737/72079184-726df400-3320-11ea-9931-38ac6417ad08.png)

Further I was looking for schedule.css file , it is not in css module .. can you help with that

**Comment by Dishebh** [comment]
You can try making changes in the application.scss file which you will find in the `src/backend/scss/` directory.

**Comment by Dishebh** [comment]
Also, you can generate the test page by switching to the gh-pages branch on the repo or by uploading a sample zip file in the website generator.

**Comment by Dishebh** [comment]
@ektaarora3501 any progress? You can file a pr when done with changes.

**Comment by yyash01** [comment]
Hey, is this issue is still open, can I work on this?

**Comment by Dishebh** [comment]
Sure

**Comment by Raunaksingh100** [comment]
i am working on this issue @mariobehling can you plz review this issue

**Comment by iamareebjamal** [comment]
How does someone review an issue?

**Comment by Raunaksingh100** [comment]
@iamareebjamal can you add codeheat label for this issue ?

**Comment by Raunaksingh100** [comment]
@iamareebjamal and @Dishebh you can closed this issue because i fixed this issue.

**Comment by anjali1102** [comment]
Is this issue closed? Anyone working on it?

**Comment by Raunaksingh100** [comment]
@anjali1102 no i already fixed this isse see my pr #2379

**Comment by Raunaksingh100** [comment]
> Is this issue closed? Anyone working on it?

@anjali1102  this issue now fixed and i already fixed this issue see my pr #2379
