### ISSUE TITLE
Misalignment of radio buttons 

### ISSUE THREAD

**Issue by Dishebh** [fossasia/open-event-wsgen#2162]
**Actual Behaviour**
When clicked on the `GENERATE WEBAPP` button, the radio buttons get misaligned w.r.t. each other.

**Expected Behaviour**
There should be no misalignment between the radio buttons.

**Screenshots of the issue**
![Screenshot from 2020-01-06 19-38-21](https://user-images.githubusercontent.com/43489708/71823200-b2cd3800-30bc-11ea-8e35-e4f9ffafc230.png)

**Would you like to work on the issue?**
Yes

**Comment by jlegha** [comment]
Upload via FTP button seems to be moving from its place when we add a zip file otherwise I don't see any kind of issue when we click on GENERATE WEBAPP.

 If you can tell me more about this the issue that would help me.

**Comment by Dishebh** [comment]
> Upload via FTP button seems to be moving from its place when we add a zip file otherwise I don't see any kind of issue when we click on GENERATE WEBAPP.
> 
> If you can tell me more about this issue then that would help me.

Please see the above screenshot mentioned in the issue description. 
When you click on GENERATE WEBAPP, without filling all the required fields, the radio buttons under the `Choose Session Styles` get misaligned and the validator error message doesn't have red font color. 
Please see if you can solve the issue.

**Comment by jlegha** [comment]
Would this work?

![image](https://user-images.githubusercontent.com/42602396/81552143-8f830400-93a0-11ea-9ff3-1e039feefc99.png)

**Comment by Dishebh** [comment]
> Would this work?
> 
> ![image](https://user-images.githubusercontent.com/42602396/81552143-8f830400-93a0-11ea-9ff3-1e039feefc99.png)

LGTM. Can you pls file a pr for the above changes?

**Comment by jlegha** [comment]
Will do.

**Comment by jlegha** [comment]
Pull request has been generated.

**Comment by jlegha** [comment]
Can you also help me to choose which type of zip files because there seems to be problem while extracting the zip file.

![image](https://user-images.githubusercontent.com/42602396/81594192-24f0b900-93de-11ea-88f4-1ba7d7b2c7b5.png)

**Comment by Dishebh** [comment]
> Can you also help me to choose which type of zip files because there seems to be problem while extracting the zip file.
> 
> ![image](https://user-images.githubusercontent.com/42602396/81594192-24f0b900-93de-11ea-88f4-1ba7d7b2c7b5.png)

Can you share the complete logs?

**Comment by iamareebjamal** [comment]
ZIP mode isn't working already

**Comment by digitalPlayer1125** [comment]
Hey @Dishebh, are you actively looking to the issue?

**Comment by iamareebjamal** [comment]
No

**Comment by digitalPlayer1125** [comment]
Alright, actually this issue can be closed as this problem won't arise after #2335  is addressed. In 2335, the pre-selection would never let such case occur[the alignment issue caused to both radio buttons both being unselected]. Hope it makes sense.
