### ISSUE TITLE
Get Code Climate working again

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-wsgen#2212]
**Actual Behaviour**

The configuration file is outdated for the code-climate. 

**Expected Behaviour**

Fix the configuration with the latest compatible version

**Error on Codeclimate**
codeclimate validate-config
```
ERROR: 'exclude_paths' must be one of array, string
WARNING: 'engines' has been deprecated, please use 'plugins' instead
WARNING: 'exclude_paths' has been deprecated, please use 'exclude_patterns' instead
WARNING: 'ratings' has been deprecated, and will not be used
```

Documentation https://docs.codeclimate.com/docs/configuring-your-code-climate-analysis

Links:
https://codeclimate.com/github/fossasia/open-event-wsgen/builds/

**Comment by amansohal8654** [comment]
can i work on it?

**Comment by iamareebjamal** [comment]
Not needed
