### ISSUE TITLE
Generated Page: Search bar out of place

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2214]
The search bar is out of place on generated pages. See below. 

Compare https://summit.fossasia.org/event/tracks.html

![Screenshot from 2020-03-02 13-12-29](https://user-images.githubusercontent.com/1583873/75675505-93e7be00-5c87-11ea-8981-5bb3050ea6af.png)

**Comment by mohak852** [comment]
Can I work on this issue?

**Comment by djcruz93** [comment]
I am working on this issue.
