### ISSUE TITLE
Generator Creates Images for Rejected Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2228]
The website generator adds images of speakers that are rejected into the images folder. This is not necessary.

**Comment by djcruz93** [comment]
@mariobehling @iamareebjamal  Can you please explain this a bit more? How can I reproduce this issue?

**Comment by djcruz93** [comment]
From where do we get to know if a speaker is rejected? In case of session rejected we do have a field as state in sessions json. Do we have something similar to it?

**Comment by iamareebjamal** [comment]
speaker.status === 'accepted'

**Comment by djcruz93** [comment]
> speaker.status === 'accepted'

Are referring 'status' field in speakers json? I searched in the codebase but I didn't find anything like this.
