### ISSUE TITLE
If speakers does not add a title it creates unwanted space in speaker description

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2249]
If a speakers adds both title and company things look fine on the schedule and tracks page. But, if a speaker does not add a job title there is an unwanted space after brackets, e.g. "Daniel Blueman ( FOSSASIA)" instead of  "Daniel Blueman (FOSSASIA)".

Compare below:
![Screenshot from 2020-03-18 10-39-57](https://user-images.githubusercontent.com/1583873/76919937-35684400-6905-11ea-9a8a-adb583008cf5.png)

**Comment by mohak852** [comment]
Can you write steps to reproduce this.

**Comment by Ritwik880** [comment]
Is this issue is still open, If yes then I want to fix this.

**Comment by iamareebjamal** [comment]
It's open

**Comment by yash0501** [comment]
Can I work on this issue??

**Comment by iamareebjamal** [comment]
Yes

**Comment by djcruz93** [comment]
@iamareebjamal Seems like no one is working on this at present. I would like to take up this issue. Can you please assign me this issue?

**Comment by iamareebjamal** [comment]
Please send a PR

**Comment by djcruz93** [comment]
@mariobehling @iamareebjamal I wanted to manually test my changes for this issue, so I tried running the app locally and got an error while extracting zip. Then I tried on development-version and production-version to check if there is some error in the local setup or the error is in the codebase. I am getting the same error on both the development-version and the production-version. I am able to figure out the bug. Please do let me know if a new issue needs to be created.

![](https://files.gitter.im/55637e4015522ed4b3e0ecf1/XSTs/image.png)

![](https://files.gitter.im/55637e4015522ed4b3e0ecf1/XSTs/image.png)

**Comment by iamareebjamal** [comment]
Use API method, not ZIP
