### ISSUE TITLE
Change location of video to top when session is expanded

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2253]
The video is currently below the description. It should be the other way around.

Please move the video to the top.

![Screenshot from 2020-03-20 10-25-49](https://user-images.githubusercontent.com/1583873/77131144-8313b680-6a95-11ea-8cbc-501ef78a0712.png)

**Comment by anandgupta887** [comment]
Is this still open for contribution??

**Comment by iamareebjamal** [comment]
Green means open, red means close

**Comment by anandgupta887** [comment]
okay 
can you let me know which page(url) it is to work start working

**Comment by iamareebjamal** [comment]
Sessions Page

**Comment by mohak852** [comment]
please can you write the steps to reproduce this issue

**Comment by digitalPlayer1125** [comment]
Hi again @mariobehling! I would like to take up this issue. Is it open? If yes, may you please guide me on how to go about it? Maybe in a line or two?

**Comment by yash0501** [comment]
Hey, Can I work on this issue??

**Comment by iamareebjamal** [comment]
Take up one issue at a time

**Comment by djcruz93** [comment]
@iamareebjamal again it seems like no one is working at present on this issue. I would like to take it up. Can you please assign it to me?
