### ISSUE TITLE
Speaker description width is not 100%

### ISSUE THREAD

**Issue by Manish-Kumarr** [fossasia/open-event-wsgen#2322]
**Actual Behaviour**
.speaker-description(Class) width is not the full width of display or 100%

**Expected Behaviour**
width will 100% of class .speaker-description

**Steps to reproduce it**
1. http://sched.eventyay.com/
2. Click on FOSSASIA Summit 2018
3. Then change width 50% to 100%
@media (max-width: 992px)
.speaker-with-bio .speaker-description {
    text-align: center;
    width: 100%;
}

Before here width is 50% which is not the full width of the screen that's why the text is not in the center

**Screenshots of the issue**
![WhatsApp Image 2020-07-13 at 10 57 54 AM](https://user-images.githubusercontent.com/53834930/87274525-91c92200-c4f9-11ea-854a-e16d73ffffdb.jpeg)

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by myselfpiyush** [comment]
I want to work on this .

**Comment by ayeshaqaisar** [comment]
Yes, I would like to work on this issue.

**Comment by alkatrivedi** [comment]
I would like to work on this issue. May I?

**Comment by dsnehasish74** [comment]
can I work on this

**Comment by myselfpiyush** [comment]
Yeah , sure !
