### ISSUE TITLE
Simplify Form: Take out API version, pre-select options, fix spelling

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2335]
Please simplify the form as follows:
1. Choose Session Style - pre-select "Expandable"
2. Choose Map Integration - pre-select "Open Street Map"
* Get rid of the underscore in the map names
3. Get rid of "Choose your API version". After the transfer to open event v2 we are only using API v2
4. Choose your data source - pre-select API
* Change text "Choose your data source" to "Choose Your Data Source"
* Change text "API endpoint of event on OpenEvent" to "API Endpoint"
* Change text "Link to Open Event API endpoint" to "Link to Open Event API Endpoint"
* currently the text below "Link to Open Event API endpoint" is build, change to not bold
* for the JSON option currently the text "Zip file containing resources for the event" is bold, change it to non-bold
5. Change text of the form field of Google Analytics and Calendar as follows
* "google analytics id" to "Google Analytics ID"
* "google calendar..." to "Google Calendar ..."

Please provide a **test link** to allow reviewers to test changes quickly.

![Screenshot from 2020-08-19 17-56-31](https://user-images.githubusercontent.com/1583873/90659917-8d54ff00-e245-11ea-9631-e06b1f96f83b.png)

![Screenshot from 2020-08-19 18-00-21](https://user-images.githubusercontent.com/1583873/90660194-e15fe380-e245-11ea-9598-5a0c8824b76a.png)

**Comment by HADES-01** [comment]
@mariobehling I would love to work this issue. Please assign it to me.
