### ISSUE TITLE
Fix and re-enable sponsor link test

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-wsgen#2362]
A test in test/sessionEventAndCoC.js was disabled to fix the build in https://github.com/fossasia/open-event-wsgen/pull/2361

Fix the logic and re-enable the test

**Comment by djcruz93** [comment]
@iamareebjamal there is one sponsor link endpoint which has been removed by the sponsor. There are two ways either we can remove the sponsor form the event site data or we can test for Mozilla All Hands 2017 event site broken sponsor links. Let me know what do I need to do I'll do it.

**Comment by iamareebjamal** [comment]
Second option
