### ISSUE TITLE
Website Generation not working with sample event zip file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2390]
The website generation using an event zip file exported from eventyay.com is currently not working.

Please export an event from eventyay and try to generate an event to reproduce this issue.

![Screenshot from 2020-11-10 10-40-38](https://user-images.githubusercontent.com/1583873/98656832-6ccaab80-2341-11eb-8dbd-aa8dd302527e.png)

**Comment by djcruz93** [comment]
Claiming it
