### ISSUE TITLE
SASS optimizations 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-wsgen#990]
- [ ] Remove redundancy by using SASS mixins
- [ ] Adding repeated values like padding, margin, colors etc to config.scss
- [x] Removing inline CSS from handlebars and adding it to SASS.

**Comment by utkarshnath** [comment]
@aayusharora can I work on this

**Comment by aayusharora** [comment]
Sure, @utkarshnath  will be great if you can do so :)

**Comment by SparshBansal** [comment]
@aayusharora  , I can also work with @utkarshnath  on this issue

**Comment by aayusharora** [comment]
Sure @SparshBansal Please coordinate with @utkarshnath

**Comment by utkarshnath** [comment]
"Adding repeated values like padding, margin, colors etc to config.scss "
@aayusharora do you want me to add all padding,margins used to config.scss

**Comment by utkarshnath** [comment]
@aayusharora do you want to add all values to config.scss or only frequently used values

**Comment by aayusharora** [comment]
@utkarshnath My idea is to write mixins and call them whenever needed for padding, margin etc.

**Comment by geekyd** [comment]
@aayusharora @Princu7  The inline CSS is not removed completely from all the pages. This is partially solved. please reopen it.

**Comment by geekyd** [comment]
@agbilotia1998 @ParthS007 Can you have a look at this?

**Comment by ParthS007** [comment]
sure @geekyd , will check this and let you know about the progress 👍

**Comment by varun560** [comment]
@aayusharora  Can i work on this issue?

**Comment by aayusharora** [comment]
Sure @varun560 
Go ahead :)
